config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'account', sign_up: 'register' }, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get 'account', to: 'registrations#show'
  end

  root to: 'site#index'
  get 'manage', to: 'site#manage'

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :images, only: [:destroy]
  end

  resources :categories

  resources :galleries do
    resources :images, only: [:create, :destroy]
  end

  resources :roles, only: [:index, :show] do
    resources :permissions, only: [:index, :create, :destroy]
  end
end

app/views/shared/_article_preview.html.slim
- hide_details ||= false
.smallvertoffset id="article-#{article.id}" class="#{'unpublished' unless article.published?}"
  .header
    = link_to article.title, article
  .area: table.wide: tbody
    tr
      td valign='top'
        .middlevertoffset
          - unless article.abstract.to_s.empty?
            = article.abstract
          - else
            = sanitize(article.body.gsub('</', ' </'), tags: [])[0, 200] + '...'
        - unless hide_details
          .middlevertoffset: small = "Опубликовано Sandra, #{article.created_at}"

      td style='text-align: right;'
        - if article.images.any?
          = link_to article, class: 'linkimage'
            = image_tag article.images.first.thumb_url, class: 'smalloffset'
    - if can? :modify, article
      tr: td colspan='2' style='text-align: right;'
        .smalloffset
          =' link_to t('helpers.links.edit'), edit_article_path(article), class: 'btn btn-mini'
          = link_to t('helpers.links.destroy'), article_path(article), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-mini btn-danger'

app/views/shared/_comments.html.slim
.smallvertoffset
  .single-header = 'Комментарии'

.comments
  - article.comments.each do |comment|
    .smallvertoffset id="comment-#{comment.id}"
      .leftheader
        span =' 'Комментарий от: '
        span: strong =' comment.user.nickname
        span =' comment.created_at
      .area
        = comment.body
        - if can? :destroy, comment
          .actions = link_to t('helpers.links.destroy'), article_comment_path(article, comment), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-mini btn-danger'

  .smallvertoffset
    .leftheader: strong = 'Оставьте свой комментарий:'
    .area.new-comment
      = form_for [article, Comment.new], html: { class: 'form-horizontal' } do |f|
        = f.hidden_field :article_id, value: article.id
        = f.label :body
        = f.text_area :body, class: 'comment-field', rows: '5'
        .actions = f.submit t('helpers.links.send'), class: 'btn btn-primary'

app/views/shared/_login_box.html.slim
#loginbox
  .contentLB
    - if user_signed_in?
      .welcomebox
        .middleoffset = current_user.email
        .middleoffset = link_to 'Профиль', account_path
        .middleoffset = link_to 'Выход', destroy_user_session_path, method: :delete
    - else
      = simple_form_for User.new, as: 'user', url: session_path('user'), html: { class: 'form-horizontal' } do |f|
        = f.input :email
        = f.input :password
        = f.submit 'Войти', class: 'btn'
        =' link_to user_omniauth_authorize_path(:vkontakte), class: 'btn social'
          i.fa.fa-lg.fa-vk
        = link_to user_omniauth_authorize_path(:facebook), class: 'btn social'
          i.fa.fa-lg.fa-facebook
      .smalloffset
        = link_to 'Регистрация', new_user_registration_path
      .smalloffset
        = link_to 'Восстановить пароль', new_user_password_path

app/views/shared/_soul_calendar.html.slim
= image_tag 'soulcalendar/sc_05.png', class: 'soulcalendar_image'
.area
  .smallvertoffset
    .ImgAuthorSoulCalendar = 'Анастасия Боронина "Бабочка"'
    .headerSoulCalendar = 'Май'
    .headerSoulCalendar = '2 неделя'
    .textSoulCalendar
      p = 'Как найти себя? Этот допрос волнует сегодня многих. В прежние времена условия жизни были проще и понятнее, сегодня все усложнилось. Трудности начинаются при выборе профессии. Подросток, знающий, кем он хочет стать, — это уже, пожалуй, исключение из правила. И не всегда находит он возможность учиться, чтобы работать именно там, где ему хотелось бы. Таким образом, взросление растягивается порой до тридцати лет, а некоторые вообще никогда не становятся по-настоящему совершеннолетними. Часто думают, что можно найти себя, если больше заниматься собой, но это вообще не так. Скорее, станешь законченным эгоистом. На самом деле, чтобы найти себя, надо внимательно всматриваться в мир и учиться все глубже понимать его.'
      p = 'Ведь  человек — это совокупность всего, что есть в мире. Если я обращаюсь к миру, то я обращаюсь к себе. Мир же начинается с самых близких  людей; вспомним слова заповеди: «Возлюби ближнего своего, как самого себя», т. е. учись как можно глубже чувствовать, что твой ближний — с тобою одно. Стань с ним одним целым, тогда ты соединишься с собой. К такому переживанию мира, подводящему нас все ближе к самим себе, обращает нас штайнеровский «Календарь души».'
    .authorSoulCalendar = 'Дитер Хорнеман «Душа с землею вместе дышит»'

app/views/shared/_validation_errors.html.slim
#error_explanation
  ul
    - model_class = resource.class
    - resource.errors.each do |attr, msg|
      - if resource.errors[attr].first == msg
        li.alert.alert-error = "#{model_class.human_attribute_name(attr)} #{msg}"