config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'account', sign_up: 'register' }, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get 'account', to: 'registrations#show'
  end

  root to: 'site#index'
  get 'manage', to: 'site#manage'

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :images, only: [:destroy]
  end

  resources :categories

  resources :galleries do
    resources :images, only: [:create, :destroy]
  end

  resources :roles, only: [:index, :show] do
    resources :permissions, only: [:index, :create, :destroy]
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  validates :title, presence: true

  has_many :images, as: :imageable

  default_scope { order('created_at DESC') }

  accepts_nested_attributes_for :images

  paginates_per 10
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  respond_to :html
  inherit_resources
  authorize_resource

  layout 'two_columns', only: [:new, :create, :edit, :update]

  def index
    @galleries = Gallery.page params[:page]
  end

  private

  def build_resource_params
    [params.fetch(:gallery, {}).permit(:title, images_attributes: [:id, :imageable_id, :source])]
  end
end

app/views/galleries/_form.html.slim
- breadcrumb :edit_gallery, @gallery

= simple_form_for @gallery, html: { class: 'form-horizontal', multipart: true } do |f|
  = f.input :title
  .controls
    - @gallery.images.each do |image|
      .smallvertoffset id="image-#{image.id}"
        = image_tag image.thumb_url
        '
        = link_to t('helpers.links.destroy'), image, method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-mini btn-danger'

  = f.label :images
  .controls
    = f.simple_fields_for :images, @gallery.images.build do |i|
      = i.file_field :source

  .actions
    = f.submit t('helpers.links.save'), class: 'btn btn-primary'
    '
    = link_to t('helpers.links.cancel'), galleries_path, class: 'btn'

app/views/galleries/_image.html.slim
a href=image.source_url data-ngthumb=image.thumb_url
  = image_tag image.thumb_url

app/views/galleries/edit.html.slim
- model_class = Gallery
.header = t '.title'
.area = render partial: 'form'

app/views/galleries/index.html.slim
- model_class = Gallery
- breadcrumb :galleries

.galleries
  - @galleries.each do |gallery|
    .header = link_to gallery.title, gallery
    .area.middleoffset
      .center
        - gallery.images[0..1].each do |image|
          = link_to gallery, class: 'linkimage'
            =' image_tag image.thumb_url

  = paginate @galleries

  .smallvertoffset = link_to t('helpers.links.new'), new_gallery_path, class: 'btn btn-primary'

app/views/galleries/new.html.slim
- model_class = Gallery
.header = t '.title'
.area = render partial: 'form'

app/views/galleries/show.html.slim
- model_class = Gallery
- breadcrumb :gallery, @gallery

div id="gallery-#{@gallery.id}"
  .header
    = @gallery.title
  .area
    .middlevertoffset
      - if @gallery.images.any?
        #nanoGallery
          = render @gallery.images

    - if can? :modify, @gallery
      .middlevertoffset
        = form_for [@gallery, Image.new] do |f|
          = f.label :source, 'Добавить фотографии:'
          = f.file_field :source, multiple: true, name: 'image[source]'

      .middlevertoffset
        = link_to t('helpers.links.back'), galleries_path, class: 'btn'
        '
        = link_to t('helpers.links.edit'), edit_gallery_path(@gallery), class: 'btn btn-primary'
        '
        = link_to t('helpers.links.destroy'), gallery_path(@gallery), method: 'delete', data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-danger'