config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'account', sign_up: 'register' }, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get 'account', to: 'registrations#show'
  end

  root to: 'site#index'
  get 'manage', to: 'site#manage'

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :images, only: [:destroy]
  end

  resources :categories

  resources :galleries do
    resources :images, only: [:create, :destroy]
  end

  resources :roles, only: [:index, :show] do
    resources :permissions, only: [:index, :create, :destroy]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, :priority, presence: true
  validates :title, uniqueness: { case_sensitive: false }

  has_many :articles
  has_one :image, as: :imageable

  accepts_nested_attributes_for :image
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :html
  inherit_resources
  authorize_resource

  layout 'two_columns', only: [:new, :edit, :index]

  def new
    @category = Category.new
    @category.build_image
  end

  def edit
    edit! { @category.build_image unless @category.image }
  end

  def index
    @categories = Category.order(:priority)
  end

  def create
    create!(notice: t('activerecord.successful.messages.category_saved'))
  end

  def update
    update!(notice: t('activerecord.successful.messages.category_saved'))
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.visible.page params[:page]
  end

  private
    def build_resource_params
      [params.fetch(:category, {}).permit(:title, :description, :priority, image_attributes: [:id, :imageable_id, :source])]
    end
end

app/views/categories/_form.html.slim
- breadcrumb :edit_category, @category
= simple_form_for @category, html: { class: 'form-horizontal', multipart: true } do |f|
  = f.input :title
  = f.input :description
  = f.input :priority
  - if @category.image.persisted?
    .control-group
      = f.label :image
      .controls
        = image_tag @category.image.thumb_url
  = f.simple_fields_for :image do |i|
    = i.input :source, as: :file

  .actions
    = f.submit t('helpers.links.save'), class: 'btn btn-primary'
    '
    = link_to t('helpers.links.cancel'), categories_path, class: 'btn'

app/views/categories/edit.html.slim
- model_class = Category

.header = t '.title'
.area = render partial: 'form'

app/views/categories/index.html.slim
- model_class = Category
- breadcrumb :categories

.header = t '.title'
.area
  table.table.table-striped
    thead.list-header
      tr
        th = model_class.human_attribute_name(:priority)
        th = model_class.human_attribute_name(:title)
        th = model_class.human_attribute_name(:articles_count)
        th = model_class.human_attribute_name(:description)

    tbody.list
      - @categories.each do |category|
        tr.list-item id = "category-#{category.id}"
          td = category.priority
          td = link_to category.title, category
          td = category.articles.size
          td = category.description
          td
            = link_to t('helpers.links.edit'), edit_category_path(category), class: 'btn btn-mini'
            '
            = link_to t('helpers.links.destroy'), category_path(category), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-mini btn-danger'

  = link_to t('helpers.links.new'), new_category_path, class: 'btn btn-primary'

app/views/categories/new.html.slim
- model_class = Category

.header = t '.title'
.area = render partial: 'form'

app/views/categories/show.html.slim
- model_class = Category
- breadcrumb :category, @category

- if can? :modify, @category
  div id="category-#{@category.id}"
    .smallvertoffset
      .header = @category.title

      .area
        .smallvertoffset = @category.description if @category.description
        .smallvertoffset = image_tag @category.image.thumb_url if @category.image

        .actions
          = link_to t('helpers.links.back'), categories_path, class: 'btn'
          '
          = link_to t('helpers.links.edit'), edit_category_path(@category), class: 'btn'
          '
          = link_to t('helpers.links.destroy'), category_path(@category), method: 'delete', data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-danger'

.articles
  - @articles.each do |article|
    = render partial: 'shared/article_preview', locals: { article: article }

  = paginate @articles